swagger: "2.0"
info:
  description: "Telecom Hackathon | Build Your App 48hrs Game!\n Build a MiniFlow App Backend"
  version: "0.0.1"
  title: "HackathonT3 | UltraNanoFlow"
  contact:
    email: "kimbuz@teco.com.ar"

host: "bkultrananoflow.herokuapp.com"
basePath: "/api/v1"

paths:
  /user/login:
    post:
      tags:
      - "user"
      summary: "Validate account and return Cookies"
      description: ""
      operationId: "login"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Session validation"
        required: true
      responses:
        "200":
          description: "Login ok"
        "401":
          description: "Authorized"
        
  /user/signup:
    post:
      tags:
      - "user"
      summary: "Create new account on server"
      description: ""
      operationId: "signup"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for User Creation"
        required: false
      responses:
        "200":
          description: "Login ok"
        "400":
          description: "Missing Data / Email Already Taken"
        "500":
          description: "Something Fail... Check the error"

  /user/logout:
    get:
      tags:
      - "user"
      summary: "Drop Session Cookies"
      description: ""
      operationId: "logout"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Session Drop"
        required: false
      responses:
        "200":
          description: "Login out"

  /content:
    get:
      tags:
      - "content"
      summary: "Get list of Content Json"
      description: ""
      operationId: "content"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content List All"
        required: false
      responses:
        "200":
          description: "Json Output"

  /content/premieres:
    get:
      tags:
      - "content"
      summary: "Get list of Content premieres Json"
      description: ""
      operationId: "contentpremieres"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content premieres List All"
        required: false
      responses:
        "200":
          description: "Json Output"

  /content/movies:
    get:
      tags:
      - "content"
      summary: "Get list of Content movies Json"
      description: ""
      operationId: "contentmovies"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content movies List All"
        required: false
      responses:
        "200":
          description: "Json Output"

  /content/series:
    get:
      tags:
      - "content"
      summary: "Get list of Content series Json"
      description: ""
      operationId: "contentseries"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content series List All"
        required: false
      responses:
        "200":
          description: "Json Output"

  /content/genres:
    get:
      tags:
      - "content"
      summary: "Get list of genres Json"
      description: ""
      operationId: "contentgenres"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for genres List All"
        required: false
      responses:
        "200":
          description: "Json Output"


  /content/random:
    get:
      tags:
      - "content"
      summary: "Get Random Content info"
      description: ""
      operationId: "contentrandom"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for random Content Id info"
        required: false
      responses:
        "200":
          description: "Json Output"


  /content/genres/:genre:
    get:
      tags:
      - "content"
      summary: "Get Specific Content for Genre info"
      description: ""
      operationId: "contentgenres:genre"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content for Genre info"
        required: false
      responses:
        "200":
          description: "Json Output"

  /content/:id:
    get:
      tags:
      - "content"
      summary: "Get Specific Content info"
      description: ""
      operationId: "content:id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Api for Content Id info"
        required: false
      responses:
        "200":
          description: "Json Output"
          
definitions:
  Content:
    type: "object"
    properties:
      _id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
        format: "string"
      year:
        type: "integer"
        format: "int64"
      info: 
        type: "object"
        properties:
          directors: 
            type: string
            example: ["str1", "str2", "str3"]
          release_date: 
            type: string
            format: Date
          rating:
            type: "integer"
            format: "int64"
          genres: 
            type: string
            example: ["str1", "str2", "str3"]
          image_url:
            type: string
          plot:
            type: string
          rank:
            type: "integer"
            format: "int64"
          running_time_secs:
            type: "integer"
            format: "int64"
          actors:
            type: string
            example: ["str1", "str2", "str3"]
          trailer_url: 
            type: string
          movie_url:
            type: string
          type:
            type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"